name: 'france_data_market'
version: '1.0.0'
config-version: 2

profile: 'france_data_market'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  france_data_market:
    staging:
      +materialized: view
    marts:
      +materialized: table
